FROM debian:latest

RUN apt-get update && apt-get install -y curl fish git

RUN curl -sS https://starship.rs/install.sh | sh -s -- --yes

RUN curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz

RUN gunzip elm.gz

RUN chmod +x elm

RUN mv elm /usr/local/bin/

RUN useradd -ms /usr/bin/fish bdoliveira

USER bdoliveira

WORKDIR /home/bdoliveira

RUN mkdir -p .config/fish/

RUN echo "add_newline = false" >> .config/starship.toml

RUN echo "set fish_greeting" >> .config/fish/config.fish

RUN echo "starship init fish | source" >> .config/fish/config.fish
